### ISSUE TITLE
Server Crash on Start!

### ISSUE THREAD

**Issue by Nick1Z2** [AlexDocking/XP-Benefits#1]
Failed to start the server. Exception was Exception: Exception
Message:H:\Steam\steamapps\common\Eco Server\Mods\UserCode\XP Benefits\Objects\TreeObject.override.cs(40,11): error CS0101: Der Namespace "Eco.Mods.Organisms" enthält bereits eine Definition für "TrunkPiece".
Source:Eco.ModKit

System.Exception: H:\Steam\steamapps\common\Eco Server\Mods\UserCode\XP Benefits\Objects\TreeObject.override.cs(40,11): error CS0101: Der Namespace "Eco.Mods.Organisms" enthält bereits eine Definition für "TrunkPiece".
   at Eco.ModKit.RoslynCompiler.HandleCompilerError(ImmutableArray`1 diagnostics)
   at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
   at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.

**Comment by AlexDocking** [comment]
The file path should just be "Mods\UserCode\Objects\TreeObject.override.cs". You don't need to move any folders about, the zip file has the correct folder structure and you can copy it to your server directory so that the "Mods" folders combine
