### ISSUE TITLE
Server crash on start due to change in MinimapManager Object API (Eco v10.2.3)

### ISSUE THREAD

**Issue by craisis** [AlexDocking/XP-Benefits#2]
Eco removed MinimapManager.Objects, replacing it with MinimapManager.DeltaHashSetObjects. 

On loading ModKit fails with the following error

```
Message:/home/container/server/Mods/UserCode/Objects/TreeObject.override.cs(209,36): error CS0119: 'ArrayUtils.Objects(Array)' is a method, which is not valid in the given context
Source:Eco.ModKit

System.Exception: /home/container/server/Mods/UserCode/Objects/TreeObject.override.cs(209,36): error CS0119: 'ArrayUtils.Objects(Array)' is a method, which is not valid in the given context
   at Eco.ModKit.RoslynCompiler.HandleCompilerError(ImmutableArray`1 diagnostics)
   at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
   at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
```

**Comment by AlexDocking** [comment]
Hi, this indeed broke in 10.2.3. Thanks for the pull request 😄
